import { Banner } from "../components/Banner"
import { TextOffset } from "../components/TextOffset"

export default function privacyPolicyPage(){
  return(
    <main>
      <Banner title="Politicas de privacidad" desc=""/>
      
      <TextOffset content='Last updated: November 17, 2023' line={true} br={true}/>
      <TextOffset content='This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.' line={true} br={true}/>

      <TextOffset content='Interpretation and Definitions' upper={true} line={true} br={true}/>
      <TextOffset content='Interpretation' upper={true} line={true} br={true}/>

      <TextOffset content='The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.' line={true} br={true}/>
      
      <TextOffset content='Definitions' upper={true} line={true} br={true}/>
      <TextOffset content='For the purposes of this Privacy Policy:' line={true} br={true}/>

      <TextOffset content='- means a unique account created for You to access our Service or parts of our Service.' line={true} br={true}/>
      <TextOffset content='- means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.' line={true} br={true}/>
      <TextOffset content='- (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Dvloped.' line={true} br={true}/>
      <TextOffset content='- are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.' line={true} br={true}/>
      <TextOffset content='- refers to:  Colombia' line={true} br={true}/>
      <TextOffset content='- means any device that can access the Service such as a computer, a cellphone or a digital tablet.' line={true} br={true}/>
      <TextOffset content='- is any information that relates to an identified or identifiable individual.' line={true} br={true}/>
      <TextOffset content='- refers to the Website.' line={true} br={true}/>
      <TextOffset content='- means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.' line={true} br={true}/>
      <TextOffset content='- refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).' line={true} br={true}/>
      <TextOffset content='- means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.' line={true} br={true}/>

      
    </main>
  )
}
